# Travis CI (https://travis-ci.org/) configuration
language: node_js
node_js:
  - "lts/*" # latest LTS Node.js release
script:
  - vue-cli-service build
  - vue-cli-service electron:build
deploy:
  provider: releases
  file: ["dist_electron/travistest 0.1.0.AppImage", "dist_electron/travistest_0.1.0_amd64.snap"]
  skip_cleanup: true
  on:
    branch: electron
