# Travis CI (https://travis-ci.org/) configuration
language: node_js
node_js:
  - "lts/*" # latest LTS Node.js release
script:
  - vue-cli-service build
deploy:
  - provider: releases
    github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
    file: ["travistest 0.1.0.AppImage", "travistest_0.1.0_amd64.snap"]
    skip_cleanup: true
    on:
      branch: electron
